version: "3.9"

services:
  postgres:
    image: postgres:16
    restart: always
    container_name: personalized-horoscope-db
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: zodiac
      POSTGRES_DB: horoscope
    ports:
      - "5400:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
