export enum AuthCode {
  USER_REGISTERED = "USER_REGISTERED",
  USER_LOGGED_IN = "USER_LOGGED_IN",
  EMAIL_ALREADY_EXISTS = "EMAIL_ALREADY_EXISTS",
  USER_NOT_FOUND = "USER_NOT_FOUND",
  INVALID_CREDENTIALS = "INVALID_CREDENTIALS",
  UNAUTHORIZED = "UNAUTHORIZED",
}

export enum HoroscopeCode {
  HOROSCOPE_TODAY_FETCHED = "HOROSCOPE_TODAY_FETCHED",
  HOROSCOPE_NOT_FOUND = "HOROSCOPE_NOT_FOUND",
}

export enum GenericCode {
  INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
  TOO_MANY_REQUESTS = "TOO_MANY_REQUESTS",
  BAD_REQUEST = "BAD_REQUEST",
}
